Repository mathics/Mathics, pull requests merged in 2020-08, with the labels that each got.

#523 Quit and Exit
  mathics/builtin/assignment.py
  mathics/builtin/evaluation.py
  mathics/main.py
Labels: enhancement

#809 Fixed the annoying 'Eigenvalues' bug that is making builds fail
  mathics/builtin/linalg.py
Labels: bug, enhancement

#806 Implement Wolfram's Root builtin
  mathics/builtin/calculus.py
  mathics/core/convert.py
Labels: bug, enhancement, needs review

#600 Graph[]
  mathics/algorithm/clusters.py
  mathics/builtin/__init__.py
  mathics/builtin/graphics.py
  mathics/builtin/graphs.py
  mathics/core/parser/operators.py
  mathics/core/parser/tokeniser.py
  mathics/core/util.py
Labels: enhancement

#776 Add some types
  .gitignore
  .travis.yml
  mathics/builtin/base.py
  mathics/builtin/inout.py
  mathics/core/definitions.py
  mathics/core/evaluation.py
  mathics/core/expression.py
  mathics/core/numbers.py
  mathics/core/rules.py
  mathics/core/util.py
  setup.py
Labels: needs review

#696 Adding new functions (Check, Interrupt, Unique) to Mathics
  mathics/builtin/control.py
  mathics/builtin/inout.py
  mathics/builtin/scoping.py
Labels: enhancement
