Repository mathics/Mathics, pull requests merged in 2020-09, with the labels that each got.

#816 Expanded Expand
  mathics/builtin/algebra.py
Labels: enhancement

#817 Implemented proper sympolic expantion for the Re and Im builtins
  mathics/builtin/arithmetic.py
Labels: enhancement

#705 Add Association
  mathics/builtin/lists.py
  mathics/core/parser/parser.py
  mathics/core/parser/tokeniser.py
  test/test_parser/test_parser.py
  test/test_parser/test_tokeniser.py
Labels: needs review

#688 Adding SubsetQ and Delete function
  mathics/builtin/base.py
  mathics/builtin/lists.py
Labels: enhancement, needs work

#819 Fixed the behaviour of `Quit`
  mathics/builtin/evaluation.py
Labels: enhancement

#618 Information
  mathics/builtin/assignment.py
  mathics/core/parser/operators.py
  mathics/core/parser/parser.py
  mathics/core/parser/tokeniser.py
  mathics/doc/doc.py
  test/test_parser/test_parser.py
  test/test_parser/test_tokeniser.py
Labels: enhancement

#821 Upgraded to sympy 1.6
  .travis.yml
  mathics/builtin/arithmetic.py
  mathics/builtin/diffeqns.py
  mathics/builtin/linalg.py
  mathics/builtin/numbertheory.py
  mathics/builtin/recurrence.py
  mathics/core/convert.py
  setup.py
Labels: enhancement, meta

#824 Refactoring the sorting of the results of Eigenvalues and Eigenvectors
  mathics/builtin/linalg.py
Labels: enhancement

#827 Fixed a bug in the evaluation of `SympyPrime`
  mathics/core/convert.py
  mathics/main.py
  mathics/script.py
  mathics/server.py
Labels: bug

#828 Updated the information about licensing and contributors
  AUTHORS.txt
  mathics/__init__.py
Labels: enhancement, meta

#829 Show chapter/sections in test.py
  mathics/test.py
Labels: enhancement, meta

#832 Remove deprecation warning associated with \
  mathics/builtin/diffeqns.py
  mathics/builtin/exptrig.py
  mathics/builtin/files.py
  mathics/builtin/inout.py
Labels: bug, enhancement

#837 Fixed bug in Quit[]
  mathics/core/definitions.py
Labels: bug

#838 Added mentation about docker images in the documentation
  README.rst
Labels: docs, enhancement

#848 InputForm should escape backslash
  mathics/builtin/files.py
  mathics/builtin/inout.py
  mathics/builtin/lists.py
  mathics/core/expression.py
Labels: bug, enhancement

#858 Update PyPI Python index for supported version
  setup.py
Labels: enhancement, meta

#856 Partial fix for documentation
  .travis.yml
  mathics/doc/doc.py
  mathics/doc/images.sh
  mathics/doc/tex/Makefile
Labels: bug

#855 Add BarChart, PieChart, and DensityPlot
  mathics/builtin/plot.py
  setup.py
Labels: enhancement

#862 Fix documentation errors regarding UTF8
  .travis.yml
  mathics/doc/doc.py
  mathics/doc/tex/Makefile
  mathics/doc/tex/latexmkrc
  mathics/doc/tex/mathics.tex
Labels: enhancement, meta

#863 Use pydot for Graphs...
  mathics/builtin/graphs.py
  setup.py
Labels: enhancement, meta

#865 Add $Package
  mathics/builtin/system.py
  mathics/core/definitions.py
Labels: enhancement

#864 Add new gallery examples, remove broken ones
  mathics/web/media/js/inout.js
Labels: docs, enhancement

#869 Sum product fix
  mathics/builtin/arithmetic.py
  mathics/core/expression.py
Labels: bug

#873 Added exemples to the documentation of `Sum` and `Product`
  mathics/builtin/arithmetic.py
Labels: docs, enhancement

#876 Doc and build improvements
  .gitignore
  Makefile
  README.rst
  admin-tools/git2cl
  admin-tools/release.sh
  mathics/doc/Makefile
  mathics/doc/images.sh
  mathics/doc/tex/Makefile
  mathics/doc/tex/mathics.tex
  test/test_console.py
  tox.ini
Labels: docs, enhancement, meta

#872 Fix several of the asymptote errors
  .travis.yml
  mathics/builtin/__init__.py
  mathics/builtin/assignment.py
  mathics/builtin/graphics.py
  mathics/doc/tex/latexmkrc
  mathics/doc/tex/mathics.tex
Labels: bug, docs

#877 Add Github Actions
  .github/workflows/basic.yml
Labels: enhancement, meta

#881 Update README.rst
  README.rst
Labels: bug, docs

#880 Update .travis.yml
  .travis.yml
  mathics/builtin/__init__.py
  mathics/doc/tex/mathics.tex
Labels: enhancement, meta

#886 Fixed missing file error in write_latex()
  .travis.yml
  Makefile
  mathics/doc/tex/Makefile
Labels: bug, docs, meta

#693 Add RealDigits
  .travis.yml
  mathics/builtin/numeric.py
Labels: enhancement, needs rabase, needs work

#895 In-memory sessions
  mathics/core/evaluation.py
  mathics/web/models.py
  mathics/web/views.py
Labels: enhancement

#623 In-memory sessions
  mathics/core/evaluation.py
  mathics/web/models.py
  mathics/web/views.py
Labels: needs rabase, performance

#897 Fixing llvm
  .travis.yml
Labels: bug, enhancement, meta

#894 Fix #861
  setup.py
Labels: bug, enhancement, meta

#898 Give warnings when using options not supported by a Builtin (#645 rebase)
  mathics/builtin/base.py
  mathics/builtin/graphics.py
  mathics/builtin/importexport.py
  mathics/builtin/lists.py
  mathics/builtin/options.py
  mathics/builtin/plot.py
  mathics/core/expression.py
  mathics/core/rules.py
Labels: enhancement

#899 Update to Django 2.2
  CHANGES.rst
  mathics/core/definitions.py
  mathics/doc/doc.py
  mathics/doc/utils.py
  mathics/settings.py
  mathics/web/migrations/0002_auto_20200917_2354.py
  mathics/web/models.py
  mathics/web/views.py
  pymathics/natlang/README.rst
  pymathics/natlang/__init__.py
  pymathics/natlang/natlang.py
  pymathics/natlang/test.py
  pymathics/pymathics/__init__.py
  pymathics/pymathics/natlang/doc/1-Manual.mdoc
  setup.py
Labels: enhancement, meta

#903 Fixpymathicsdoc
  .travis.yml
  mathics/builtin/assignment.py
  mathics/core/expression.py
  mathics/doc/doc.py
Labels: bug

#902 Support for open files from internet
  mathics/builtin/arithmetic.py
  mathics/builtin/assignment.py
  mathics/builtin/files.py
  mathics/builtin/graphics.py
  mathics/builtin/numeric.py
  mathics/core/expression.py
  mathics/core/pattern.py
  mathics/core/rules.py
  setup.py
  test/test_parser/test_tokeniser.py
Labels: enhancement

#907 Fixed #906
  mathics/doc/doc.py
  pymathics/natlang/__init__.py
Labels: bug

#913 Default name for pymathics modules
  mathics/doc/doc.py
Labels: enhancement, meta

#914 adding Import for M packages
  mathics/autoload/formats/PACKAGE/Import.m
Labels: enhancement, meta

#919 Downgrade Django
  CHANGES.rst
  mathics/doc/utils.py
  mathics/settings.py
  mathics/web/migrations/0003_auto_20200921_1835.py
  mathics/web/models.py
  mathics/web/views.py
  setup.py
Labels: bug, meta

#917 Remove Graphs from the master branch
  CHANGES.rst
  mathics/builtin/__init__.py
  mathics/builtin/graphs.py
Labels: meta

#918 Remove Combinatorica from the master branch
  CHANGES.rst
  mathics/packages/Combinatorica/Combinatorica.m
  mathics/packages/Combinatorica/Kernel/init.m
Labels: meta

#908 Sansserif
  mathics/autoload/formats/SVG/Export.m
  mathics/builtin/__init__.py
  mathics/builtin/inout.py
  mathics/doc/documentation/1-Manual.mdoc
Labels: enhancement

#921 Remove most references to mathics.net and mathics.org
  COPYING.txt
  mathics/builtin/importexport.py
  mathics/doc/documentation/1-Manual.mdoc
  mathics/web/templates/base.html
Labels: docs, meta

#924 Add SystemTimeZone, adjust TimeZone..
  CHANGES.rst
  mathics/builtin/__init__.py
  mathics/builtin/datentime.py
  mathics/builtin/evaluation.py
  mathics/core/expression.py
Labels: enhancement

#929 Update the links in the documentation to point to mathics.org
  COPYING.txt
  README.rst
  mathics/doc/documentation/1-Manual.mdoc
  mathics/web/templates/main.html
  pymathics/setup.py
  setup.py
Labels: docs, enhancement, meta

#930 Fix bug in the Cross implementation
  mathics/builtin/linalg.py
Labels: bug

#922 Implement the DiscreteLimit builtin
  CHANGES.rst
  mathics/builtin/calculus.py
Labels: enhancement

#685 Adding function Subsets to the mathics
  mathics/builtin/combinatorial.py
Labels: enhancement, needs review, needs work
