Repository mathics/Mathics, pull requests merged in 2020-10, with the labels that each got.

#936 Qtime
  mathics/builtin/algebra.py
  mathics/builtin/arithmetic.py
  mathics/builtin/assignment.py
  mathics/builtin/combinatorial.py
  mathics/builtin/files.py
  mathics/builtin/functional.py
  mathics/builtin/lists.py
  mathics/builtin/numeric.py
  mathics/builtin/quantities.py
  mathics/builtin/strings.py
  mathics/builtin/structure.py
  mathics/builtin/tensors.py
  mathics/core/definitions.py
  mathics/core/expression.py
  mathics/core/pattern.py
  mathics/core/rules.py
  mathics/core/util.py
  mathics/doc/utils.py
  mathics/web/models.py
  pymathics/natlang/natlang.py
Labels: enhancement, performance

#938 Add Environment[name] and Environment[]
  CHANGES.rst
  mathics/Makefile
  mathics/builtin/system.py
Labels: enhancement

#939 Allow passing back source-code lines..
  mathics/core/evaluation.py
  mathics/core/parser/util.py
Labels: enhancement

#937 Fix runtime bugs seen from GS3.m in per_expr()
  mathics/core/pattern.py
Labels: bug

#928 Revise docker setup instructions
  README.rst
  app/Dockerfile
  app/entrypoint.sh
  app/requirements-tmathics.txt
  app/requirements.txt
  docker-compose.yml
  mathics/settings.py
Labels: docs, meta

#948 Sections for what's not there and why...
  CHANGES.rst
  mathics/__init__.py
Labels: docs, enhancement

#959 Fix #958
  mathics/web/media/js/prototype/prototype.js
Labels: bug, docs, web interface

#964 Hook in Gries & Schneider test into test suite
  Makefile
  examples/symbolic_logic/gries_schneider/GS1.m
  examples/symbolic_logic/gries_schneider/GS2.m
  examples/symbolic_logic/gries_schneider/GS3.m
  examples/symbolic_logic/gries_schneider/test-gs.sh
Labels: enhancement, meta

#967 fix Get/Put test
  mathics/builtin/files.py
Labels: bug

#966 Importatmodule
  mathics/builtin/assignment.py
  mathics/builtin/files.py
  mathics/builtin/importexport.py
  mathics/core/characters.py
Labels: bug

#972 adding tests for Exit,Quit and file operations
  test/test_evaluation.py
  test/test_file.py
Labels: enhancement, meta

#977 Remove implementation details from user-facing documentation
  mathics/doc/documentation/1-Manual.mdoc
  mathics/doc/documentation/images/classes.png
Labels: docs

#975 Doc building simplify
  Makefile
  mathics/builtin/compilation.py
  mathics/builtin/inout.py
  mathics/doc/doc.py
  mathics/doc/tex/Makefile
Labels: enhancement, meta

#976 Add documentation about the "Generate Hash" button
  mathics/doc/documentation/1-Manual.mdoc
  mathics/web/templates/base.html
Labels: docs, enhancement

#981 More doc updates 2
  mathics/builtin/attributes.py
Labels: docs, enhancement

#968 Simpler, reduced TravisCI
  .travis.yml
  Makefile
  travis.py
Labels: meta

#991 Fix #989
  mathics/core/parser/tokeniser.py
Labels: bug

#993 Fix ldots
  mathics/builtin/patterns.py
Labels: bug

#994 Set directory fixes
  mathics/builtin/files.py
  mathics/builtin/system.py
Labels: bug
