Repository mathics/Mathics, pull requests merged in 2020-11, with the labels that each got.

#1001 Mathicssession
  mathics/session.py
  test/test_evaluation.py
Labels: enhancement

#1019 Improvedeletecases
  mathics/builtin/lists.py
  test/test_deletecases.py
Labels: enhancement

#1020 adding support for bool in from_python
  mathics/core/expression.py
Labels: enhancement

#1028 More tests, More doc, less duplication
  mathics/builtin/scoping.py
  test/helper.py
  test/test_combinatorica.py
  test/test_control.py
  test/test_evaluation.py
Labels: bug, enhancement

#1026 fix compile
  mathics/builtin/compilation.py
Labels: bug, enhancement

#1032 Add contributed package RSolve
  mathics/builtin/inout.py
  mathics/builtin/recurrence.py
  mathics/packages/DiscreteMath/Kernel/init.m
  mathics/packages/DiscreteMath/RSolve.m
Labels: enhancement

#1031 numpy matrix is deprecated so remove it
  mathics/builtin/pympler/asizeof.py
Labels: enhancement, meta

#1029 Combinatorica again
  mathics/builtin/control.py
  mathics/builtin/files.py
  mathics/builtin/scoping.py
  mathics/core/evaluation.py
  mathics/packages/DiscreteMath/CombinatoricaV0.6.m
  mathics/packages/DiscreteMath/Kernel/init.m
  test/test_control.py
Labels: enhancement
